### ISSUE TITLE
添付ファイルの削除

### ISSUE THREAD

**Issue by s7n12** [efwGrp/skeQA#1]
一覧から項目を削除した際に、添付ファイルも削除する機能

**Comment by changkejun** [comment]
create_listPage_delete
create_selectDialog_delete
![image](https://github.com/user-attachments/assets/33d5cfa5-6526-4b2d-9f0b-067e81444165)

**Comment by changkejun** [comment]
```
    if (file.exists("K001/"+old社員番号+"/"+old対象年月)){
        file.remove("K001/"+old社員番号+"/"+old対象年月);
    }
```
![image](https://github.com/user-attachments/assets/65d4ccd4-5bf6-4997-84de-4e9fb01e3730)
